class CropCondition {
  final String name;
  final List<String> rainfall;
  final List<String> soilType;
  final List<String> climate;
  final List<String> season;

  CropCondition({
    required this.name,
    required this.rainfall,
    required this.soilType,
    required this.climate,
    required this.season,
  });
}

List<CropCondition> cropConditions = [
  CropCondition(
    name: 'Wheat',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Rice',
    rainfall: ['Abundant'],
    soilType: ['Clay', 'Silt'],
    climate: ['Tropical'],
    season: ['Summer', 'Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Maize',
    rainfall: ['Medium', 'Less/No Rain'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate', 'Dry'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Barley',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Cotton',
    rainfall: ['Abundant'],
    soilType: ['Saline', 'Sandy', 'Loamy'],
    climate: ['Tropical', 'Dry'],
    season: ['Summer'],
  ),
  CropCondition(
    name: 'Soybean',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Sugarcane',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Clay', 'Silt'],
    climate: ['Tropical', 'Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Millet',
    rainfall: ['Less/No Rain'],
    soilType: ['Sandy', 'Loamy', 'Saline'],
    climate: ['Dry'],
    season: ['Summer'],
  ),
  CropCondition(
    name: 'Mango',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Grape',
    rainfall: ['Abundant', 'Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Turmeric',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Clay'],
    climate: ['Tropical'],
    season: ['Summer', 'Autumn'],
  ),
  CropCondition(
    name: 'Peanut',
    rainfall: ['Medium'],
    soilType: ['Sandy', 'Loamy', 'Clay'],
    climate: ['Tropical'],
    season: ['Summer'],
  ),
  CropCondition(
    name: 'Sunflower',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Carrot',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Potato',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Tomato',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer', 'Autumn'],
  ),
  CropCondition(
    name: 'Cucumber',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Tropical'],
    season: ['Summer'],
  ),
  CropCondition(
    name: 'Chili',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Tropical'],
    season: ['Summer'],
  ),
  CropCondition(
    name: 'Garlic',
    rainfall: ['Less/No Rain'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Onion',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Papaya',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Banana',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Silt', 'Clay'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Pineapple',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Cabbage',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Silt', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Cauliflower',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Silt', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Tea',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Clay'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Coffee',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Avocado',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Peach',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Orange',
    rainfall: ['Abundant'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Apple',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Spinach',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Broccoli',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Lettuce',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Pepper',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Strawberry',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Blueberry',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Raspberry',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy', 'Clay'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Blackberry',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Cherry',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Plum',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Pear',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Melon',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Watermelon',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Pomegranate',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Dragon Fruit',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Kiwi',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Passion Fruit',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Guava',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Fig',
    rainfall: ['Medium'],
    soilType: ['Loamy', 'Sandy'],
    climate: ['Temperate', 'Tropical'],
    season: ['Spring', 'Summer'],
  ),
  CropCondition(
    name: 'Peas',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Loamy'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn','Summer'],
  ),
  CropCondition(
    name: 'Chickpeas',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Saline'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn', 'Summer'],
  ),
  CropCondition(
    name: 'Lentils',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Silt'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Oats',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Loamy'],
    climate: ['Tropical'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Buckwheat',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Loamy'],
    climate: ['Temperate'],
    season: [ 'Summer'],
  ),
  CropCondition(
    name: 'Barley',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Loamy'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Green Beans',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Loamy'],
    climate: [ 'Tropical'],
    season: ['Spring', 'Autumn'],
  ),
  CropCondition(
    name: 'Red Beans',
    rainfall: ['Medium'],
    soilType: ['Clay', 'Loamy'],
    climate: ['Temperate'],
    season: ['Spring', 'Autumn'],
  ),
];

List<String> recommendCrops({
  required String rainfall,
  required String soilType,
  required String climate,
  required String season,
}) {
  List<String> recommendations = [];

  for (var crop in cropConditions) {
    if (crop.rainfall.contains(rainfall) &&
        crop.soilType.contains(soilType) &&
        crop.climate.contains(climate) &&
        crop.season.contains(season)) {
      recommendations.add(crop.name);
    }
  }

  return recommendations;
}
