// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbJt-kwmAu8eCRZ7NFqT3u6-E5ixrIixQ',
    appId: '1:113595036036:web:f86edae94875a722c12dd1',
    messagingSenderId: '113595036036',
    projectId: 'rythu-mithra-7e444',
    authDomain: 'rythu-mithra-7e444.firebaseapp.com',
    storageBucket: 'rythu-mithra-7e444.appspot.com',
    measurementId: 'G-RW7EBRP9CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hY-GjvKzbDlUfHsn4rB316vfweAa58s',
    appId: '1:113595036036:android:1cb64b9ad053cb45c12dd1',
    messagingSenderId: '113595036036',
    projectId: 'rythu-mithra-7e444',
    storageBucket: 'rythu-mithra-7e444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJKMjwpkB63tAMEt-xzGbFdCv48ijfus',
    appId: '1:113595036036:ios:f071abdd235c11f7c12dd1',
    messagingSenderId: '113595036036',
    projectId: 'rythu-mithra-7e444',
    storageBucket: 'rythu-mithra-7e444.appspot.com',
    iosBundleId: 'com.example.rythuMithra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJKMjwpkB63tAMEt-xzGbFdCv48ijfus',
    appId: '1:113595036036:ios:f071abdd235c11f7c12dd1',
    messagingSenderId: '113595036036',
    projectId: 'rythu-mithra-7e444',
    storageBucket: 'rythu-mithra-7e444.appspot.com',
    iosBundleId: 'com.example.rythuMithra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbJt-kwmAu8eCRZ7NFqT3u6-E5ixrIixQ',
    appId: '1:113595036036:web:8838b39216bcba46c12dd1',
    messagingSenderId: '113595036036',
    projectId: 'rythu-mithra-7e444',
    authDomain: 'rythu-mithra-7e444.firebaseapp.com',
    storageBucket: 'rythu-mithra-7e444.appspot.com',
    measurementId: 'G-K1XKRMJKW2',
  );
}
